#pragma once

#include <vector>
#include "glad/glad.h"
#include "GLFW/glfw3.h"

constexpr int HURT_NUM_KEYS = 350;

namespace hurt {
	void updateKeys(GLFWwindow * window);
};

bool hurtKeyPressed(int key);
bool hurtKeyDown(int key);
bool hurtKeyReleased(int key);

constexpr int HURT_KEY_UNKNOWN = GLFW_KEY_UNKNOWN;
constexpr int HURT_KEY_SPACE = GLFW_KEY_SPACE;
constexpr int HURT_KEY_APOSTROPHE = GLFW_KEY_APOSTROPHE;
constexpr int HURT_KEY_COMMA = GLFW_KEY_COMMA;
constexpr int HURT_KEY_MINUS = GLFW_KEY_MINUS;
constexpr int HURT_KEY_PERIOD = GLFW_KEY_PERIOD;
constexpr int HURT_KEY_SLASH = GLFW_KEY_SLASH;
constexpr int HURT_KEY_0 = GLFW_KEY_0;
constexpr int HURT_KEY_1 = GLFW_KEY_1;
constexpr int HURT_KEY_2 = GLFW_KEY_2;
constexpr int HURT_KEY_3 = GLFW_KEY_3;
constexpr int HURT_KEY_4 = GLFW_KEY_4;
constexpr int HURT_KEY_5 = GLFW_KEY_5;
constexpr int HURT_KEY_6 = GLFW_KEY_6;
constexpr int HURT_KEY_7 = GLFW_KEY_7;
constexpr int HURT_KEY_8 = GLFW_KEY_8;
constexpr int HURT_KEY_9 = GLFW_KEY_9;
constexpr int HURT_KEY_SEMICOLON = GLFW_KEY_SEMICOLON;
constexpr int HURT_KEY_EQUAL = GLFW_KEY_EQUAL;
constexpr int HURT_KEY_A = GLFW_KEY_A;
constexpr int HURT_KEY_B = GLFW_KEY_B;
constexpr int HURT_KEY_C = GLFW_KEY_C;
constexpr int HURT_KEY_D = GLFW_KEY_D;
constexpr int HURT_KEY_E = GLFW_KEY_E;
constexpr int HURT_KEY_F = GLFW_KEY_F;
constexpr int HURT_KEY_G = GLFW_KEY_G;
constexpr int HURT_KEY_H = GLFW_KEY_H;
constexpr int HURT_KEY_I = GLFW_KEY_I;
constexpr int HURT_KEY_J = GLFW_KEY_J;
constexpr int HURT_KEY_K = GLFW_KEY_K;
constexpr int HURT_KEY_L = GLFW_KEY_L;
constexpr int HURT_KEY_M = GLFW_KEY_M;
constexpr int HURT_KEY_N = GLFW_KEY_N;
constexpr int HURT_KEY_O = GLFW_KEY_O;
constexpr int HURT_KEY_P = GLFW_KEY_P;
constexpr int HURT_KEY_Q = GLFW_KEY_Q;
constexpr int HURT_KEY_R = GLFW_KEY_R;
constexpr int HURT_KEY_S = GLFW_KEY_S;
constexpr int HURT_KEY_T = GLFW_KEY_T;
constexpr int HURT_KEY_U = GLFW_KEY_U;
constexpr int HURT_KEY_V = GLFW_KEY_V;
constexpr int HURT_KEY_W = GLFW_KEY_W;
constexpr int HURT_KEY_X = GLFW_KEY_X;
constexpr int HURT_KEY_Y = GLFW_KEY_Y;
constexpr int HURT_KEY_Z = GLFW_KEY_Z;
constexpr int HURT_KEY_LEFT_BRACKET = GLFW_KEY_LEFT_BRACKET;
constexpr int HURT_KEY_BACKSLASH = GLFW_KEY_BACKSLASH;
constexpr int HURT_KEY_RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET;
constexpr int HURT_KEY_GRAVE_ACCENT = GLFW_KEY_GRAVE_ACCENT;
constexpr int HURT_KEY_WORLD_1 = GLFW_KEY_WORLD_1;
constexpr int HURT_KEY_WORLD_2 = GLFW_KEY_WORLD_2;
constexpr int HURT_KEY_ESCAPE = GLFW_KEY_ESCAPE;
constexpr int HURT_KEY_ENTER = GLFW_KEY_ENTER;
constexpr int HURT_KEY_TAB = GLFW_KEY_TAB;
constexpr int HURT_KEY_BACKSPACE = GLFW_KEY_BACKSPACE;
constexpr int HURT_KEY_INSERT = GLFW_KEY_INSERT;
constexpr int HURT_KEY_DELETE = GLFW_KEY_DELETE;
constexpr int HURT_KEY_RIGHT = GLFW_KEY_RIGHT;
constexpr int HURT_KEY_LEFT = GLFW_KEY_LEFT;
constexpr int HURT_KEY_DOWN = GLFW_KEY_DOWN;
constexpr int HURT_KEY_UP = GLFW_KEY_UP;
constexpr int HURT_KEY_PAGE_UP = GLFW_KEY_PAGE_UP;
constexpr int HURT_KEY_PAGE_DOWN = GLFW_KEY_PAGE_DOWN;
constexpr int HURT_KEY_HOME = GLFW_KEY_HOME;
constexpr int HURT_KEY_END = GLFW_KEY_END;
constexpr int HURT_KEY_CAPS_LOCK = GLFW_KEY_CAPS_LOCK;
constexpr int HURT_KEY_SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK;
constexpr int HURT_KEY_NUM_LOCK = GLFW_KEY_NUM_LOCK;
constexpr int HURT_KEY_PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN;
constexpr int HURT_KEY_PAUSE = GLFW_KEY_PAUSE;
constexpr int HURT_KEY_F1 = GLFW_KEY_F1;
constexpr int HURT_KEY_F2 = GLFW_KEY_F2;
constexpr int HURT_KEY_F3 = GLFW_KEY_F3;
constexpr int HURT_KEY_F4 = GLFW_KEY_F4;
constexpr int HURT_KEY_F5 = GLFW_KEY_F5;
constexpr int HURT_KEY_F6 = GLFW_KEY_F6;
constexpr int HURT_KEY_F7 = GLFW_KEY_F7;
constexpr int HURT_KEY_F8 = GLFW_KEY_F8;
constexpr int HURT_KEY_F9 = GLFW_KEY_F9;
constexpr int HURT_KEY_F10 = GLFW_KEY_F10;
constexpr int HURT_KEY_F11 = GLFW_KEY_F11;
constexpr int HURT_KEY_F12 = GLFW_KEY_F12;
constexpr int HURT_KEY_F13 = GLFW_KEY_F13;
constexpr int HURT_KEY_F14 = GLFW_KEY_F14;
constexpr int HURT_KEY_F15 = GLFW_KEY_F15;
constexpr int HURT_KEY_F16 = GLFW_KEY_F16;
constexpr int HURT_KEY_F17 = GLFW_KEY_F17;
constexpr int HURT_KEY_F18 = GLFW_KEY_F18;
constexpr int HURT_KEY_F19 = GLFW_KEY_F19;
constexpr int HURT_KEY_F20 = GLFW_KEY_F20;
constexpr int HURT_KEY_F21 = GLFW_KEY_F21;
constexpr int HURT_KEY_F22 = GLFW_KEY_F22;
constexpr int HURT_KEY_F23 = GLFW_KEY_F23;
constexpr int HURT_KEY_F24 = GLFW_KEY_F24;
constexpr int HURT_KEY_F25 = GLFW_KEY_F25;
constexpr int HURT_KEY_KP_0 = GLFW_KEY_KP_0;
constexpr int HURT_KEY_KP_1 = GLFW_KEY_KP_1;
constexpr int HURT_KEY_KP_2 = GLFW_KEY_KP_2;
constexpr int HURT_KEY_KP_3 = GLFW_KEY_KP_3;
constexpr int HURT_KEY_KP_4 = GLFW_KEY_KP_4;
constexpr int HURT_KEY_KP_5 = GLFW_KEY_KP_5;
constexpr int HURT_KEY_KP_6 = GLFW_KEY_KP_6;
constexpr int HURT_KEY_KP_7 = GLFW_KEY_KP_7;
constexpr int HURT_KEY_KP_8 = GLFW_KEY_KP_8;
constexpr int HURT_KEY_KP_9 = GLFW_KEY_KP_9;
constexpr int HURT_KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL;
constexpr int HURT_KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE;
constexpr int HURT_KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY;
constexpr int HURT_KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT;
constexpr int HURT_KEY_KP_ADD = GLFW_KEY_KP_ADD;
constexpr int HURT_KEY_KP_ENTER = GLFW_KEY_KP_ENTER;
constexpr int HURT_KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL;
constexpr int HURT_KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT;
constexpr int HURT_KEY_LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL;
constexpr int HURT_KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT;
constexpr int HURT_KEY_LEFT_SUPER = GLFW_KEY_LEFT_SUPER;
constexpr int HURT_KEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT;
constexpr int HURT_KEY_RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL;
constexpr int HURT_KEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT;
constexpr int HURT_KEY_RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER;
constexpr int HURT_KEY_MENU = GLFW_KEY_MENU;
constexpr int HURT_KEY_LAST = GLFW_KEY_LAST;